---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgres"    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31200 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
      - name: postgres
        image: mdillon/postgis
        ports:
        - containerPort: 5432 
        env:
          - name: DATA_DIR
            value: /tmp/postgres/data
        volumeMounts:
          - mountPath: "/tmp/postgres/data"
            name: postgres-pv-storage         