---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31200 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
      - name: postgres
        image: postgis/postgis:12-master
        ports:
        - containerPort: 5432 
        env:
          - name: DATA_DIR
            value: /tmp/postgres/data
          - name: POSTGRES_PASSWORD
            value: mysecretpassword  
        volumeMounts:
          - mountPath: "/tmp/postgres/data"
            name: db-pv-storage         