---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv-volume
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgres"    
