apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: localstack

commonLabels:
  domain: localstack
  service: localstack
  env: local

resources:
  - namespace.yaml
  - deployment.yaml
  