---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: localstack-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/localstack"    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localstack-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  type: NodePort
  ports:
  - port: 30100
    protocol: TCP
    name: ui
    nodePort: 30100
  - port: 30110
    protocol: TCP
    name: secretsmanager
    nodePort: 30110
  - port: 30120
    protocol: TCP
    name: cloudformation
    nodePort: 30120
  - port: 30130
    protocol: TCP
    name: dynamodb
    nodePort: 30130  
  # add other required aws services similarly
  #- port: 30503
  #  protocol: TCP
  #  name: s3
  #  nodePort: 30503  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: localstack-pv-storage
          persistentVolumeClaim:
            claimName: localstack-pv-claim
      containers:
      - name: localstack
        image: localstack/localstack:0.10.5
        ports:
        - containerPort: 30100 # localstack ui
        - containerPort: 30110 # secretsmanager            
        - containerPort: 30120 # cloudformation
        - containerPort: 30130 #Dynamo DB
        env:
          - name: SERVICES
            value: "secretsmanager:30110,cloudformation:30120,dynamodb:30130"
          - name: PORT_WEB_UI
            value: "30100"
          - name: DATA_DIR
            value: /tmp/localstack/data
        volumeMounts:
          - mountPath: "/tmp/localstack/data"
            name: localstack-pv-storage         